<?php if(session_status() == PHP_SESSION_NONE){
    session_start();
} ?>
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
          integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
          crossorigin=""/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/marker.css">
    <link rel="stylesheet" href="css/button.css">
    <title>Carte</title>
  </head>
  <body>

    <nav class="navbar navbar-dark bg-primary mb-3">
        <h1 class="navbar-brand">Où et quand voir les équipes de sport nantaises en 2018/2019</h1>
        <?php if(!isset($_SESSION['Auth'])): ?>
      <a href="login.php" class="navbar-brand">Login</a>
      <?php else: ?>
          <a href="logout.php" class="navbar-brand">Logout</a>
      <?php endif; ?>
    </nav>

    <a href="calendar.php">
      <div class="styled-button calend-button">
        <i class="fas fa-calendar-alt"></i>
        <span>calendrier</span>
      </div>
    </a>

    <div class="main-content">
      <div class="list">
          <?php foreach($clubs as $club): ?>
            <div class="item js-marker js-club-<?= $club['id']?>" data-lat="<?= $club['latitude'] ?>" data-lng="<?= $club['longitude'] ?>"  data-competition="<?= $club['competition']  ?>" data-logo="<?= $club['logo']?>" data-name="<?= $club['name'] ?>" data-stadium="<?= $club['stadium'] ?>" data-id="<?= $club['id'] ?>" data-address="<?= $club['address'] ?>" ")>
            
              <img  class="item-logo" src="img/<?= $club['logo']?>" alt="">
              <a target="_blank" class="club__link" href="<?= $websites[$club['id']-1] ?>">Site officiel</a>
              <hr class='card-separator'>
              <?php if ($club['preview'] == true) :?>
                <h4>Prochain match</h4>
                <?php foreach($club['matches'] as $match) :?>
                    <div class='event'>
                      <ul class='match-infos'>
                        <li class='match-detail'>
                          <img class="stadium-icon" src="img/scoreboard.png" alt="">
                          <?=  $match['teams'] ?><?=  var_dump($match['teams']) ?>
                        </li>
                        <div class="matchtime">
                          <li class='match-detail'>
                            <img class="stadium-icon" src="img/calendar.png" alt="">
                            <?=  $match['day'] ?>
                          </li>
                          <li class='match-detail'>
                            <img class="stadium-icon" src="img/clock.png" alt="">
                            <?=  $match['weekday'] ?> - <?=  $match['hour'] ?>
                          </li>
                        </div>
                      </ul>
                    </div>
                <?php endforeach ?>
              <?php else :?>
                <h4>Pas de match à venir</h4>
              <?php  endif ?>
            </div>
          <?php endforeach ?>
      </div>
      <div class="map" id="map"></div>
    </div>
    <script src="js/utilities.js"></script>
    <script src="js/vendor.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>

<?php require '../views/footer.php'; ?>
<!-- <div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div> -->


<!-- <div>Icons made by <a href="https://www.flaticon.com/authors/srip" title="srip">srip</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div> -->

<!-- <div>Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div> -->

<!-- <div>Icons made by <a href="https://www.flaticon.com/authors/becris" title="Becris">Becris</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div> -->

<!-- Twitter -->

<!-- <div>Icons made by <a href="https://www.flaticon.com/authors/smalllikeart" title="smalllikeart">smalllikeart</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div> -->